#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
Delete:
  path: medic_prescription_delete
  controller: App\Controller\MedicPrescriptionController::delete
  methods: delete

