#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#app_lucky_number:
#  path: /appointment
#  controller: App\Controller\profiles\AppointmentController
login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
Delete:
  path: medic_prescription_delete
  controller: App\Controller\MedicPrescriptionController::delete
  methods: delete

